const j = $json;
const p = $('Redaktions-Check').first().json;
const nowIso = $now.toISO();
return [{ json: {
  cp_id: 'cp_' + Date.now(),
  marketing_idea_ref: (p.mi_id && p.mi_id !== '__none__') ? p.mi_id : null,
  use_case_ref: (p.uc_id && p.uc_id !== '__none__') ? p.uc_id : null,
  created_at: nowIso,
  pillar: p.pillar,
  source_mode: p.source_mode,
  topic: p.topic,
  target_group: p.target_group,
  why_now: p.why_now,
  content_score: p.content_score,
  qa_passed: !!p.qa_passed,
  qa_issues: String(p.qa_issues||''),
  linkedin_text: p.linkedin_text,
  linkedin_hashtags: p.linkedin_hashtags,
  instagram_text: p.instagram_text,
  instagram_hashtags: p.instagram_hashtags,
  instagram_alt: p.instagram_alt,
  facebook_text: p.facebook_text,
  link_comment_text: p.link_comment_text,
  analyse_notiz: ('Slot: ' + String(p.slot_name||'') + ' | ' + String(p.analyse_notiz||'')),
  recommended_platform: p.recommended_platform,
  posting_order: p.posting_order,
  visual_type: 'image',
  visual_status: 'generated',
  image_prompt: j.image_prompt,
  video_recommended: j.video_recommended,
  video_package: j.video_package,
  mi_id: p.mi_id, uc_id: p.uc_id,
  slot_name: p.slot_name,
  available_in_slot: p.available_in_slot,
  praxis_beispiel: p.praxis_beispiel,
  selection_note: p.selection_note,
  sources: (p.source_url ? (p.source + ' \u2014 ' + p.source_url) : (p.source_mode === 'use_case' ? 'Eigener Use-Case (' + p.uc_id + ')' : p.source)),
  status: (p.qa_passed ? 'ready_for_review' : 'needs_rework')
} }];