// Einmalwerkzeug vom 04.09.2026: legt sechs Handwerk-Use-Cases an.
// Die Saeule handwerk hatte null offene Eintraege, der Dienstagsslot fiel
// deshalb auf Ersatzsaeulen zurueck. Die Texte sind mit dem echten Code aus
// "Thema waehlen" geprueft (probe_handwerk.js) und erreichen je 100 Punkte.
// Quelle: flows/kapa-content-studio/entwurf/handwerk_use_cases.json
const jetzt = $now.toISO();
const eintraege = [
  {"uc_id": "uc_1788540000000_1", "name": "Aufmass von der Baustelle in die Angebotsposition", "pillar": "handwerk", "target_group": "Trockenbau- und Malerbetriebe", "problem": "Das Aufmaß wird auf der Baustelle handschriftlich notiert, im Büro abgetippt und dann in die Angebotspositionen übertragen. Jeder Übertrag ist eine Fehlerquelle, und eine Rückfrage zum Aufmaß kostet den Bauleiter einen zweiten Weg zur Baustelle.", "solution": "Das Aufmaß wird auf der Baustelle einmal erfasst und wandert ohne Abtippen in die Angebotsposition. Weicht das Angebot vom Aufmaß ab, fällt das beim Erstellen auf und nicht erst bei der Schlussrechnung.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Weniger Nacharbeit an Angeboten und weniger Streit über Mengen bei der Abrechnung.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"},
  {"uc_id": "uc_1788540000000_2", "name": "Stundenzettel von der Baustelle in die Abrechnung", "pillar": "handwerk", "target_group": "Dachdecker- und Zimmereibetriebe", "problem": "Stundenzettel kommen als Foto, als Zettel oder per Zuruf ins Büro, oft erst zum Monatsende. Wer sie erfasst, muss jede Zeile dem richtigen Auftrag und der richtigen Baustelle zuordnen und bei Unklarheiten nachtelefonieren.", "solution": "Der Stundenzettel wird am Tag der Leistung erfasst und direkt dem Auftrag zugeordnet. Das Büro sieht offene Tage sofort, statt sie am Monatsende zusammenzusuchen.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Die Abrechnung wird planbar, und Leistungen gehen nicht mehr verloren, weil ein Zettel fehlt.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"},
  {"uc_id": "uc_1788540000000_3", "name": "Lieferschein dem richtigen Auftrag zuordnen", "pillar": "handwerk", "target_group": "Elektrohandwerk", "problem": "Lieferscheine vom Großhandel landen lose im Büro. Welcher Beleg zu welchem Auftrag gehört, weiß nur der Monteur, und bis zur Rechnungsprüfung ist die Zuordnung oft nicht mehr zu rekonstruieren.", "solution": "Jeder Lieferschein wird beim Eingang gelesen und dem Auftrag zugeordnet. Die Rechnungsprüfung vergleicht dann Beleg und Auftrag, statt zuerst Papier zu sortieren.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Materialkosten landen auf dem richtigen Auftrag, und Doppelzahlungen fallen bei der Prüfung auf.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"},
  {"uc_id": "uc_1788540000000_4", "name": "Nachtrag auf der Baustelle festhalten", "pillar": "handwerk", "target_group": "Rohbau- und Betonbaubetriebe", "problem": "Zusatzleistungen werden auf der Baustelle mündlich vereinbart und später nicht mehr belegt. Ohne Protokoll fällt der Nachtrag bei der Abrechnung durch, und die Leistung ist erbracht, aber nicht bezahlt.", "solution": "Der Nachtrag wird direkt auf der Baustelle mit Zeitpunkt, Beteiligten und Umfang protokolliert und an den Auftrag gehängt. Die Abrechnung greift damit auf ein Protokoll zu und nicht auf Erinnerung.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Erbrachte Zusatzleistungen werden bezahlt, statt in der Schlussrechnung unterzugehen.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"},
  {"uc_id": "uc_1788540000000_5", "name": "Wartungsplan und Pruefprotokoll an einer Stelle", "pillar": "handwerk", "target_group": "SHK-Betriebe", "problem": "Wiederkehrende Prüfungen stehen in einer Liste, im Kalender und im Kopf des Meisters. Fällige Termine fallen auf, wenn der Kunde anruft, und das Prüfprotokoll vom letzten Mal muss erst gesucht werden.", "solution": "Der Wartungsplan führt Termin, Anlage und Kunde an einer Stelle zusammen. Das Prüfprotokoll des letzten Termins hängt daran, sodass der Monteur den Vorbefund kennt, bevor er losfährt.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Wartungsverträge werden vollständig abgerufen, und der zweite Anfahrtsweg entfällt.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"},
  {"uc_id": "uc_1788540000000_6", "name": "Anfragen im Posteingang vorsortieren", "pillar": "handwerk", "target_group": "Tischlereien und Schreinereien", "problem": "Anfragen kommen per E-Mail, über das Kontaktformular und telefonisch. Im Posteingang liegen Neuanfragen, Rückfragen zu laufenden Aufträgen und Belege durcheinander, und jede Nachricht muss von Hand gelesen und zugeordnet werden.", "solution": "Der Posteingang wird vorsortiert nach Neuanfrage, Rückfrage zu einem Auftrag und Beleg. Wer antwortet, sieht die Zuordnung bereits und muss den Verlauf nicht erst suchen.", "technology": "Automatisierung und digitale Prozesse", "business_model": "Anfragen werden schneller beantwortet, und nichts bleibt im Posteingang liegen.", "score": 8, "trigger_source": "Von Hand gesetzt am 04.09.2026 - die Saeule handwerk stand auf null offenen Eintraegen", "status": "new"}
];
return eintraege.map(e => ({ json: Object.assign({}, e, {
  first_seen: jetzt,
  last_evaluated: jetzt
}) }));
